language: php

os: linux

php:
    - '7.3'

cache:
    directories:
        - ~/.composer/cache/files

install:
    - composer install --no-interaction --prefer-dist

script:
    - composer validate
    - vendor/bin/phpunit